/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gradecalculator;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author set
 */
public class Main extends javax.swing.JFrame {

    static final int MAXIMUM_DAY = 12;
    static final double MAXIMUM_MILESTONE_GRADE = 25.5;
    static final double MAXIMUM_TERMINAL_ASSESSMENT_GRADE = 34;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms2Score = new javax.swing.JTextField();
        ms2TotalScore = new javax.swing.JTextField();
        taScore = new javax.swing.JTextField();
        taTotalScore = new javax.swing.JTextField();
        present = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ms1Score = new javax.swing.JTextField();
        ms1Field = new javax.swing.JTextField();
        ms2Field = new javax.swing.JTextField();
        taField = new javax.swing.JTextField();
        attendanceField = new javax.swing.JTextField();
        ms1TotalScore = new javax.swing.JTextField();
        gradePointsField = new javax.swing.JTextField();
        percentageField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clear_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ms2Score.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms2Score.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        ms2Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms2ScoreActionPerformed(evt);
            }
        });
        getContentPane().add(ms2Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 80, 20));

        ms2TotalScore.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms2TotalScore.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        ms2TotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms2TotalScoreActionPerformed(evt);
            }
        });
        getContentPane().add(ms2TotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 80, 20));

        taScore.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        taScore.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        taScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taScoreActionPerformed(evt);
            }
        });
        getContentPane().add(taScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 80, 20));

        taTotalScore.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        taTotalScore.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        taTotalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taTotalScoreActionPerformed(evt);
            }
        });
        getContentPane().add(taTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 80, 20));

        present.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        present.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentActionPerformed(evt);
            }
        });
        getContentPane().add(present, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 170, 20));

        buttonCalculate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        buttonCalculate.setText("Calculate Grades");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel11.setText("Percentage: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel12.setText("Grade Points: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel6.setText("Final Grade:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel9.setText("Max Pts.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel10.setText("Milestone 2:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel13.setText("Terminal Assessment:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel14.setText("Attendance:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel15.setText("Course Grade:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, 20));

        jLabel17.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel17.setText("Milestone 1:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, -1, -1));

        jLabel18.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel18.setText("Milestone 2:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel19.setText("Terminal Assessment:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel20.setText("Attendance:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel21.setText("Milestone 1:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel22.setText("Present Days");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        jLabel23.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel23.setText("Score");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel24.setText("Please Fill Out the Form:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel25.setText("MMDC");

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel26.setText("GRADE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gradecalculator/Resource/images/icon.png"))); // NOI18N

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        jLabel27.setText("CALCULATOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(65, 65, 65))
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGap(112, 112, 112)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 610));

        ms1Score.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms1Score.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        ms1Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms1ScoreActionPerformed(evt);
            }
        });
        getContentPane().add(ms1Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 80, 20));

        ms1Field.setEditable(false);
        ms1Field.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms1Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ms1Field.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        ms1Field.setFocusable(false);
        ms1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms1FieldActionPerformed(evt);
            }
        });
        getContentPane().add(ms1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 80, 20));

        ms2Field.setEditable(false);
        ms2Field.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms2Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ms2Field.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        ms2Field.setFocusable(false);
        ms2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms2FieldActionPerformed(evt);
            }
        });
        getContentPane().add(ms2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 80, 20));

        taField.setEditable(false);
        taField.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        taField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        taField.setFocusable(false);
        taField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taFieldActionPerformed(evt);
            }
        });
        getContentPane().add(taField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 80, 20));

        attendanceField.setEditable(false);
        attendanceField.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        attendanceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        attendanceField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        attendanceField.setFocusable(false);
        attendanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(attendanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 80, 20));

        ms1TotalScore.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        ms1TotalScore.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        getContentPane().add(ms1TotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 80, 20));

        gradePointsField.setEditable(false);
        gradePointsField.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        gradePointsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gradePointsField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        gradePointsField.setFocusable(false);
        getContentPane().add(gradePointsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 80, 20));

        percentageField.setEditable(false);
        percentageField.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        percentageField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentageField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(209, 33, 33)));
        percentageField.setFocusable(false);
        getContentPane().add(percentageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 80, 20));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("must not exceed beyond 12");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        clear_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gradecalculator/Resource/images/clean.png"))); // NOI18N
        clear_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_iconMouseClicked(evt);
            }
        });
        getContentPane().add(clear_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gradecalculator/Resource/images/bg.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 810, 600));

        setSize(new java.awt.Dimension(1128, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void taScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taScoreActionPerformed

    private void presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentActionPerformed

    private void ms2ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms2ScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms2ScoreActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        try {
            double ms1Initial = Double.parseDouble(ms1Score.getText());
            double ms1Final = Double.parseDouble(ms1TotalScore.getText());
            double ms2Initial = Double.parseDouble(ms2Score.getText());
            double ms2Final = Double.parseDouble(ms2TotalScore.getText());
            double taInitial = Double.parseDouble(taScore.getText());
            double taFinal = Double.parseDouble(taTotalScore.getText());
            int attendance = Integer.parseInt(present.getText());

            // Validate inputs
            if (ms1Score.getText().isEmpty() || ms1TotalScore.getText().isEmpty() ||
                ms2Score.getText().isEmpty() || ms2TotalScore.getText().isEmpty() ||
                taScore.getText().isEmpty() || taTotalScore.getText().isEmpty() ||
                present.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate numeric inputs
            if (ms1Initial < 0 || ms1Final <= 0 || ms2Initial < 0 || ms2Final <= 0 || taInitial < 0 || taFinal <= 0 || attendance < 0 || attendance > MAXIMUM_DAY) {
                JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid positive integers.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate milestone and terminal assessment ranges
            if (ms1Initial > ms1Final || ms2Initial > ms2Final || taInitial > taFinal) {
                JOptionPane.showMessageDialog(this, "Initial score must be less than or equal to final score.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate attendance days
            if (attendance > MAXIMUM_DAY) {
                JOptionPane.showMessageDialog(this, "Attendance must not exceed 12 weeks.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Calculate percentages and grade points
            double mileStone1FinalScore = (ms1Initial / ms1Final) * MAXIMUM_MILESTONE_GRADE;
            double mileStone2FinalScore = (ms2Initial / ms2Final) * MAXIMUM_MILESTONE_GRADE;
            double terminalAssessmentFinalScore = (taInitial / taFinal) * MAXIMUM_TERMINAL_ASSESSMENT_GRADE;

            double initialGrades = mileStone1FinalScore + mileStone2FinalScore + terminalAssessmentFinalScore;
            double finalGrades = initialGrades + calculateAttendance(attendance);
            double gradePoint = calculateGradePoint(finalGrades);

            // Display results
            ms1Field.setText(String.format("%.2f%%", mileStone1FinalScore));
            ms2Field.setText(String.format("%.2f%%", mileStone2FinalScore));
            taField.setText(String.format("%.2f%%", terminalAssessmentFinalScore));
            attendanceField.setText(String.format("%.2f%%", calculateAttendance(attendance)));
            percentageField.setText(String.format("%.2f%%", finalGrades));
            gradePointsField.setText(String.format("%.2f", gradePoint));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid integers.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void ms2TotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms2TotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms2TotalScoreActionPerformed

    private void taTotalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taTotalScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taTotalScoreActionPerformed

    private void ms1ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms1ScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms1ScoreActionPerformed

    private void ms1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms1FieldActionPerformed

    private void ms2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms2FieldActionPerformed

    private void taFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taFieldActionPerformed

    private void attendanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceFieldActionPerformed

    private void clear_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_iconMouseClicked
        // TODO add your handling code here:
        JTextField[] textFields = { ms1Score, ms1TotalScore, ms2Score, ms2TotalScore, taScore, present, taTotalScore, percentageField, gradePointsField, ms1Field, ms2Field, taField, attendanceField};

        for (JTextField textField : textFields) {
            textField.setText("");
        }                 
    }//GEN-LAST:event_clear_iconMouseClicked
    
    public static double calculateAttendance(int attendance){
        double attendanceGrade;
        attendanceGrade = switch (attendance) {
            case 12 -> 15;
            case 11 -> 12;
            case 10 -> 9;
            case 9 -> 6;
            case 8 -> 3;
            case 7 -> 1;
            default -> 0;
        };
        return attendanceGrade;
    }
    
    public static double calculateGradePoint(double finalGrades){
        double average;
        if (finalGrades >= 96){
            average = 1.00;
        } else if (finalGrades >= 91.5){
            average = 1.25;
        } else if (finalGrades >= 87.01){
            average = 1.50;
        } else if (finalGrades >= 82.51){
            average = 1.75;
        } else if (finalGrades >= 78.01){
            average = 2.0;
        } else if (finalGrades >= 73.51){
            average = 2.25;
        } else if (finalGrades >= 69.01){
            average = 2.50;
        } else if (finalGrades >= 64.51){
            average = 2.75;
        } else if (finalGrades >= 60.00){
            average = 3.0;
        } else{
            average = 5.0;
        }
                return average;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attendanceField;
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JLabel clear_icon;
    private javax.swing.JTextField gradePointsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ms1Field;
    private javax.swing.JTextField ms1Score;
    private javax.swing.JTextField ms1TotalScore;
    private javax.swing.JTextField ms2Field;
    private javax.swing.JTextField ms2Score;
    private javax.swing.JTextField ms2TotalScore;
    private javax.swing.JTextField percentageField;
    private javax.swing.JTextField present;
    private javax.swing.JTextField taField;
    private javax.swing.JTextField taScore;
    private javax.swing.JTextField taTotalScore;
    // End of variables declaration//GEN-END:variables
}
